backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produkty"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Cena", name: "price", widget: "string" }
      - { label: "Popis", name: "description", widget: "text" }
      - { label: "Obrázek", name: "image", widget: "image" }
